Complete iter15
nessai1/linkshortener pull request #16
Opened 2023-10-29 21:05 UTC by nessai1

2023-11-04 06:21 UTC, s-shpak requested changes

2023-11-04 06:21 UTC, s-shpak commented on migrations/002_update_hash_link_table.down.sql
Миграции лучше оборачивать в транзакции

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/apiRouter.go
В go файлы принято называть либо через подчеркивания, либо через дефисы

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/linkstorage/linkStorage.go
> +	OwnerUUID *string
Зачем делать проверку наличия `UUID` через указатель на строку? В данной реализации нам не будет достаточно принять пустое значение за отсутствующее ?

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/linkstorage/linkStorage.go
> +		if link.OwnerUUID != nil && *link.OwnerUUID == userUUID {
В случае БД создается индекс для быстрого поиска по `OwnerUUID`. Как можно ускроить поиск в этом случае?

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/linkstorage/PSQLStorageDriver.go
>  func (driver *PSQLStorageDriver) Save(hl HashToLink) error {
Мне не очень нравится, что ты удаляешь данные при помощи `Save`. Почему бы не добавить в интрефейс новый метод?

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/publicRouter.go
> +	application.logger.Info(fmt.Sprintf("User auth: %s", UserUUID))
Лучше использовать With и выводить более осмысленное сообщение. Более того, это должно быть на уровне Debug: тебе не хочется в условиях нормлаьной работы сервиса забивать лог информацией о штатных событиях

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/publicRouter.go
> +		application.logger.Error(fmt.Sprintf("Cannot authorize user: %s", err.Error()))
Почитай, как лучше добавлять ошибки к сообщению `zap`

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/publicRouter.go
> +	UserUUID, err := app.Authorize(writer, request)
Авторизация должна быть в middleware

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/publicRouter.go
> +		writer.WriteHeader(403)
Используй StatusCode из пакета http

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/publicRouter.go
> +		writer.WriteHeader(http.StatusGone)
Здесь надо выйти из функции?

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/apiRouter.go
> +	cookie, err := request.Cookie(app.LoginCookieName)
Вся логика связанная с авторизацией пользователя должна быть в middleware

2023-11-04 06:21 UTC, s-shpak commented on internal/shortener/apiRouter.go
> +		err := application.storage.DeleteBatch(deleteBatch)
То есть невозможно использовать ни БД как storage, ни файловую систему? Это неправильно, ты должен иметь возможность использовать любой тип.

Сразу замечу, что удаление батчем означает, что мы в одном запросе к БД удаляем сразу несколько записей

2023-11-04 13:47 UTC, nessai1 commented on internal/shortener/apiRouter.go
done!

2023-11-04 13:52 UTC, nessai1 commented on migrations/002_update_hash_link_table.down.sql
Done!

2023-11-04 15:04 UTC, nessai1 commented on internal/shortener/linkstorage/linkStorage.go
> +		if link.OwnerUUID != nil && *link.OwnerUUID == userUUID {
Для того, чтобы не делать полный скан таблицы, надо производить поиск средствами СУБД, 
тогда и индексы станут полезными. Изначально моя архитектура была продумана под возможность использования внутренних средств СУБД для CRUD операций:

У хранилища было 3 слоя:

клиентский слой -> storage -> driver

Storage хранил в себе экземпляр драйвера, имплементирующий интерфейс StorageDriver в котором были описаны методы get/set и пр. 

Сама структура storage имела в себе все те же методы, что и интерфейc StorageDriver, и при их вызовах просто делегировала работу вложенному драйверу, получилось что-то типо стратегии. Но предыдущего ментора такая схема смутила (некоторые драйверы дублировали код, плюс список методов драйвера и storage практичи не отличались), пришлось схему переделать таким образом, что-бы слой driver'a отвечал только за операции полной загрузки данных в память и полной её выгрузки методом Save. Из-за такого пересмотра архитектуры пришлось уйти в убыток производительности, но ментор на 1-1 сказал что для учебного проекта такая архитектура будет ОК

Будет добавление в слой driver метода `findByUUID`, в обход поиску по мапе, устойчивым решением?


...или придется строить свой B-tree на уровне сервиса :D 

https://github.com/nessai1/linkshortener/pull/14#discussion_r1335229323

2023-11-04 15:07 UTC, nessai1 commented on internal/shortener/linkstorage/PSQLStorageDriver.go
>  func (driver *PSQLStorageDriver) Save(hl HashToLink) error {
Актуален ли комментарий, с учетом ответа на комментарий выше? https://github.com/nessai1/linkshortener/pull/16#discussion_r1382413225

По сути метод отвечает за полную выгрузку данных из памяти в хранилище (postgres/file), не вижу смысла отдельного метода для удаления

2023-11-04 15:23 UTC, nessai1 commented on internal/shortener/publicRouter.go
> +		writer.WriteHeader(403)
Done!

2023-11-04 15:24 UTC, nessai1 commented on internal/shortener/publicRouter.go
> +		writer.WriteHeader(http.StatusGone)
Надо бы)
Done!

2023-11-04 15:55 UTC, nessai1 commented on internal/shortener/apiRouter.go
> +		err := application.storage.DeleteBatch(deleteBatch)
> То есть невозможно использовать ни БД как storage, ни файловую систему?

Не понял вопрос. 

Сам storage умеет сохранять данные только в мапу, которая впоследствии выгружается в файловую систему / БД, в зависимости от драйвера который в ней лежит. После того как батч мапы будет модифицирован, вызывается метод Save (internal/shortener/linkstorage/linkstorage.go:122) у драйвера, который в зависимости от реализации выгружает новые данные в нужное нам место (БД/файлы)

2023-11-05 18:22 UTC, nessai1 commented on internal/shortener/publicRouter.go
> +	UserUUID, err := app.Authorize(writer, request)
Перевел на работу middleware

2023-11-05 18:23 UTC, nessai1 commented on internal/shortener/apiRouter.go
> +	cookie, err := request.Cookie(app.LoginCookieName)
Перевел на работу middleware

2023-11-05 19:51 UTC, nessai1 commented on internal/shortener/publicRouter.go
> +	application.logger.Info(fmt.Sprintf("User auth: %s", UserUUID))
Done!

2023-11-05 19:51 UTC, nessai1 commented on internal/shortener/publicRouter.go
> +		application.logger.Error(fmt.Sprintf("Cannot authorize user: %s", err.Error()))
Done!

2023-11-05 21:31 UTC, nessai1 commented on internal/shortener/linkstorage/linkStorage.go
> +	OwnerUUID *string
Перевел на работу со значением

2023-11-07 12:35 UTC, s-shpak requested changes

2023-11-07 12:35 UTC, s-shpak commented on internal/shortener/linkstorage/linkStorage.go
> +		if link.OwnerUUID != nil && *link.OwnerUUID == userUUID {
Не, писать in-memory B-tree точно не нужно :) Здесь можно было бы добавить дополнительную мапу, в которой  ключем был бы `OwnerUUID`. Но, в целом, это делать конечно не обязательно, т.к. речь действительно идет только об учебном проекте. Этот диалог можно зарезолвить

2023-11-07 12:35 UTC, s-shpak commented on internal/shortener/apiRouter.go
> +		err := application.storage.DeleteBatch(deleteBatch)
Сорри, это я неправильно понял структуру проекта, все ок

2023-11-07 12:35 UTC, s-shpak commented on go.mod
Надо обновить

2023-11-07 12:35 UTC, s-shpak commented on internal/app/auth.go
> +		cc, _ := request.Cookie(LoginCookieName)
Почему ошибки игнорируются здесь?

2023-11-07 12:35 UTC, s-shpak commented on internal/app/auth.go
> +func RequireUserUUID(request *http.Request) (string, error) {
Лучше немного по-другому: в middleware ты получаешь UserID, сохраняешь его в контекст и извлекаеш там, где это необходимо. См. здесь, как это сделать: https://medium.com/@matryer/context-keys-in-go-5312346a868d

2023-11-07 17:44 UTC, nessai1 commented on internal/app/auth.go
> +		cc, _ := request.Cookie(LoginCookieName)
Выше идет проверка 

`needToCreateSign, err := isNeedToCreateSign(request)`

Если куки нет - код попадает в условие выше

2023-11-09 18:38 UTC, nessai1 commented on internal/app/auth.go
> +func RequireUserUUID(request *http.Request) (string, error) {
done!

2023-11-09 18:38 UTC, nessai1 commented on go.mod
done!

2023-11-13 13:47 UTC, s-shpak approved these changes

2023-11-13 13:52 UTC, merged