complete iter18
nessai1/linkshortener pull request #19
Opened 2024-01-01 16:54 UTC by nessai1

2024-01-09 07:41 UTC, nessai1 commented
Не проходит тест 18го инкремента т.к. жалуется на отсутсвие доки для методов, релизующих интерфейс, а там дока и так есть :(

2024-01-09 19:06 UTC, kilchik requested changes
У тебя ведь не только про один интерфейс тест ругается - вот вывод
```
        	Error:      	Найдены файлы с недокументированной сущностями
        	Test:       	TestIteration18/TestDocsComments
        	Messages:   	internal/app/app.go:72:1
        	            	internal/app/auth.go:27:1
        	            	internal/shortener/encoder/encoder.go:7:1
        	            	internal/shortener/linkstorage/linkstorage_disk.go:17:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:13:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:23:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:28:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:47:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:51:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:68:1
        	            	internal/shortener/linkstorage/linkstorage_memory.go:80:1
        	            	internal/shortener/linkstorage/linkstorage_psql.go:20:1
        	            	internal/shortener/linkstorage/linkstorage_psql.go:37:1
        	            	internal/shortener/linkstorage/linkstorage_psql.go:83:1
        	            	internal/shortener/linkstorage/linkstorage_psql.go:88:1
        	            	internal/shortener/linkstorage/linkstorage_psql.go:119:1
        	            	internal/shortener/linkstorage/linkstorage_psql.go:145:1
        	            	internal/shortener/shortener.go:43:1
        	            	internal/shortener/shortener.go:53:1
        	            	internal/shortener/shortener.go:61:1
        	            	internal/shortener/shortener.go:65:1
```

Я выборочно прошелся по указанным строчкам, и там действительно нет godoc-комментариев (к экспортируемым методам например)

2024-01-09 19:06 UTC, kilchik commented on internal/app/app.go
> +	Production EnvType = 0
Здесь iota лучше подходит - позволяет избежать проблем с опечатками в циферках

2024-01-10 14:42 UTC, nessai1 commented on internal/app/app.go
> +	Production EnvType = 0
Точно, крутая фича) Переделал :)

2024-01-10 14:45 UTC, nessai1 commented
Добавил документации. Переосмыслил доку для методов, реализующих интерфейсы, всетаки доку для этих методов тоже надо писать, т.к. они могут и не знать о контракте который реализуют и в котором описана эта дока

2024-01-10 14:58 UTC, kilchik approved these changes

2024-01-16 15:47 UTC, merged